from .format import (
    DISCORD_MAX_LEN,
    code_block,
    json_block,
    key_value_pairs,
    pipeline_result_discord,
    section,
    split_messages,
    table_from_dicts,
    table_from_rows,
    bullet_list,
    truncate,
    format_evidence_spans_full,
    format_full_prompt_section,
    format_boundary_challenge_block,
    fenced_plain_text,
)
from .dispatcher import (
    ADJUDICATOR,
    BOUNDARY_CRITIC,
    LABEL_CODER,
    SIGNAL_EXTRACTOR,
    DISPLAY_BOT_ORDER,
    prepare_four_bot_messages,
    prepare_four_bot_messages_split,
)
from .pipeline_output import PipelineOutput

__all__ = [
    "DISCORD_MAX_LEN",
    "section",
    "table_from_rows",
    "table_from_dicts",
    "code_block",
    "json_block",
    "bullet_list",
    "key_value_pairs",
    "pipeline_result_discord",
    "split_messages",
    "truncate",
    "format_evidence_spans_full",
    "format_full_prompt_section",
    "format_boundary_challenge_block",
    "fenced_plain_text",
    # Dispatcher (1 orchestrator + 4 display bots)
    "SIGNAL_EXTRACTOR",
    "LABEL_CODER",
    "BOUNDARY_CRITIC",
    "ADJUDICATOR",
    "DISPLAY_BOT_ORDER",
    "prepare_four_bot_messages",
    "prepare_four_bot_messages_split",
    "PipelineOutput",
]
